name: VersionTinmoli
version: 1.0.1
main: com.example.versiontinmoli.VersionTinmoli
author: Author
description: A lightweight BungeeCord plugin to customize the version name displayed in the server list
