name: VersionTinmoli
version: ${version}
main: com.example.versiontinmoli.VersionTinmoli
author: Author
description: A lightweight BungeeCord plugin to customize the version name displayed in the server list
